Repository genecommerce/module-braintree-magento2, pull requests merged in 2021-07, with the labels that each got.

#63 return type CreditPriceDataInterface
  Model/ResourceModel/CreditPriceRepository.php
Labels: bugfix

#82 Phone number now pulls through to Google Pay Review page.
  Model/GooglePay/Helper/QuoteUpdater.php
Labels: bugfix, needs-review

#75 Add correct translation for gateway response
  Gateway/Command/GatewayCommand.php
Labels: bugfix, needs-review

#62 Correct bool check
  Model/Paypal/CreditApi.php
Labels: bugfix

#71 Hosted fields style basic function
  view/frontend/web/js/view/payment/adapter.js
Labels: feature, needs-review
